name: "Jest GitHub Action JL"
description: "Jest action adding checks and annotations to your pull requests and comment them with code coverage results."
branding:
  icon: "check"
  color: "green"
inputs:
  test-command:
    description: "The test command to run"
    required: false
    default: "npm test"
  working-directory:
    description: "Subdirectory to run tests in"
    required: false
    default: ""
  coverage-comment:
    description: "Comment PRs with code coverage"
    required: false
    default: "true"
  changes-only:
    description: "Only run tests on changed files (over base branch)"
    required: false
    default: "false"
  log-level:
    description: "Set the log level"
    required: false
    default: "info"

runs:
  using: "node20"
  main: "dist/index.js"
